Accident report
ianrbaguio/crash-app pull request #11
Opened 2024-03-04 18:22 UTC by memargonz

Please review accident report interface.
The environment.ts need to have a valid APIs for Google and Openweather services:

export const environment = {
    production: false,
    WEATHER_API_KEY :"",
    GOOGLE_API_KEY:"",
    GOOGLE_NEARBY_Endpoint : "https://maps.googleapis.com/maps/api/place/nearbysearch/json?",
    WEATHER_Endpoint : "https://api.openweathermap.org/data/2.5/weather?units=metric",
    PLACES_Endpoint: "https://maps.googleapis.com/maps/api/place/details/json?fields=name%2Cformatted_phone_number%2Cicon"
  };
  
Thanks

2024-03-09 17:21 UTC, ianrbaguio commented on crash/src/app/accident-report-container/intake/intake.component.ts
> +  console.log(this.Image1)
Please remove console logs

2024-03-09 17:22 UTC, ianrbaguio commented on crash/src/app/accident-report-container/map/map.component.ts
> +  /*  private spawnPlaces(landmarks:any[]){
Please remove any commented functions if they're not going to be used

2024-03-09 17:23 UTC, ianrbaguio commented on crash/src/app/accident-report-container/upload-images/upload.component.html
> +@if (message) {
When using conditional ifs in angular, please use *ngIf.

ie: <div *ngIf="message">{{ message }}</div>

2024-03-09 17:24 UTC, ianrbaguio commented on crash/src/app/crash.service.ts
> +   /* console.log(`${environment.WEATHER_Endpoint}
Please remove any commented console.logs or functions

2024-03-09 17:24 UTC, ianrbaguio requested changes
Looks good Mario, just couple of changes

2024-03-09 17:31 UTC, ianrbaguio commented on crash/src/app/accident-report-container/upload-images/upload.component.html
> +@if (message) {
It looks like this is a new way of doing *ngIf from Angular 16, please ignore this comment

2024-03-13 19:48 UTC, srtviji approved these changes
Approved

2024-03-15 14:36 UTC, ianrbaguio commented on crash/src/app/crash.service.ts
> + console.log(environment.GOOGLE_NEARBY_Endpoint)
Remove console logs

2024-03-15 14:36 UTC, ianrbaguio commented on crash/src/app/accident-report-container/map/map.component.html
> +      <!-- <google-map height="600px"
Please remove this html element if it's not going to be use anymore

2024-03-15 14:39 UTC, ianrbaguio commented on crash/src/app/accident-report-container/intake/intake.component.ts
> +    console.log("Field validations failed")
remove console log, having just the return should be okay. In the case of invalid form, we can either disable the submit button or show an error message in the front-end

2024-03-15 14:40 UTC, ianrbaguio commented on crash/src/app/accident-report-container/map/map.component.ts
> +        console.log("error caught");
remove console logs, in the case of an error we can use `throw new Error() instead`

2024-03-15 14:40 UTC, ianrbaguio commented on crash/src/app/accident-report-container/map/map.component.ts
> +        console.log(e);
same comment as above

2024-03-15 14:41 UTC, ianrbaguio commented on crash/src/app/accident-report-container/map/map.component.ts
> +          console.log(res.results);
I think we can keep this one for now, but please try to avoid using console logs

2024-03-15 15:21 UTC, merged